# -*- coding: utf-8 -*-
"""BMI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M477I_hgj7L72ZctcoqgbP0WasaqCYMo
"""

print("Welcome to Body Mass Index Calculator")
w = float(input("Enter You Weight in Kilograms: "))
h = float(input("Enter You Height in meteres: "))
bmi = w/(h*h)
print(f"Your BMI is : {bmi}")
if(bmi<18.5):
  print("Your are underweight.")
elif(bmi>18.5 and bmi<24.9):
  print("Your are Normal.")
else:
  print("Your are Overweight.")

