# -*- coding: utf-8 -*-
"""RandomPSWD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17vrIpCKAueAbCKtG99Mw7HUBXscskhm8
"""

import random

print("Welcome To Random password Generator")
i = 0
for i in range(3):
  print("...")
  i = i+1

a = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
b= "abcdefghijklmnopqrstuvwxyz"
c= "1234567890"
d= "!@#$%^&*()"
print("Select Which type of Password you want: ")
print("Type 1 if you want alphanumeric \nType 2 if you want alpanumeric with both upper and lower cases\nType 3 if you want mix password with special characters  ")
n = int(input("Your Selection: "))
if(n==1):
  password = a+c
elif(n==2):
  password = a+b+c
elif(n==3):
  password = a+b+c+d
len_pswd= int(input("Enter Length for your password: "))
ar = "".join(random.sample(password,len_pswd))
print("Your Password is : ",ar)