# -*- coding: utf-8 -*-
"""Weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rligBINKwvjM7nceQiVKpWKlYCJBiapR
"""

pip install requests

import requests

api = '1b6a65d03532f596f1824421ac717b73'

print("Welcome to Weather Information Program")
city_name = input('Enter city name or a zip code : ')
url = f'http://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api}'
data = requests.get(url)
weather = data.json()
if(data.status_code==200):
  clouds = weather['weather'][0]['main']
  clouds_des = weather['weather'][0]['description']
  temp= weather['main']['temp']
  humidity= weather['main']['humidity']
  print(f"Information of weather for {city_name}")
  print(f"Clouds:-{clouds}\nDescription of Clouds:- {clouds_des}\nTemperature:- {temp}\nHumidity:-{humidity}")
elif(data.status_code==404):
  print("Enter Valid City Name.")
else:
  print("Error Fetching Weather Report")

